name: Checks
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-linters-unit-tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'

    - name: Build
      run: time make

    - name: Linters
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.57.2
        args: --timeout 3m --verbose cmd/... pkg/...

    - name: Ensure latest install manifest
      run: |
        echo "" > dist/install.yaml
        IMG=ghcr.io/maiqueb/kubevirt-ipam-claims:latest make build-installer
        if [[ -n "$(git status --porcelain)" ]]; then
          echo "Please run 'make build-installer' and commit those changes"
          git status --porcelain
          exit 1
        fi

    - name: Test
      run: ENVTEST_VERSION="release-0.17" make test
