name: Push container image
on:
  push:
    branches:
      - main
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  push-amd64:
    name: Image push/amd64
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Version Check
        run: |
          echo "git_commit_hash=$(git describe --no-match  --always --abbrev=8 --dirty)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to Container Registry
        if: github.repository_owner == 'maiqueb'
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push latest container image
        if: github.repository_owner == 'maiqueb'
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          file: Dockerfile

      - name: Push stable container image
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          file: Dockerfile

      - name: Template release manifests
        if: startsWith(github.ref, 'refs/tags/')
        run: IMG=${{ github.ref_name }} make build-installer

      - name: Release the kraken
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            dist/install.yaml
